language: node_js
dist: xenial
os: linux
node_js:
  - 12

git:
  depth: false

stages:
  - name: test
    if: branch = master
  - name: deploy
    if: branch = master

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli

install:
  - make install

jobs:
  include:
    - stage: test
      script:
        - make test
        - echo $AWS_DEFAULT_REGION
    - stage: deploy
      script:
        - echo DEPLOY
# before_deploy:
#   - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
#   - 'unzip awscli-bundle.zip'
#   - './awscli-bundle/install -b ~/bin/aws'
#   - 'export PATH=~/bin:$PATH'
