language: node_js
dist: xenial
os: linux
node_js:
  - 12

git:
  depth: false

stages:
  - name: test
    if: branch = master
  - name: deploy
    if: branch = master

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli

install:
  - make install

jobs:
  include:
    - stage: test
      script:
        - make test
    - stage: deploy
      script:
        - make deploy
        - make build-client
        - make deploy-client
